# Robot drive type
DRIVE_TYPE = DIFFERENTIAL

# Number of wheels
WHEELS = 2

# Wheel list: wheel[index] = diametter,offsetX,offsetY,angleOfWheel, angleOfRollers
WHEEL_0 = 52,0,-156,0,90
WHEEL_1 = 52,0,156,0,90

# Motor list: motor[index] = pin1,pin2,maxSpeed,stepsPerRotations
MOTOR_0 = 6,13,700,200
MOTOR_1 = 8,11,700,200