#ifndef SILENT_EXPRTK_HPP
#define SILENT_EXPRTK_HPP

// This header is designed to suppress specific compiler warnings
// generated by the exprtk library when compiled with MSVC.

#if defined(_MSC_VER)
    // Save the current warning state
    #pragma warning(push)
    
    // Disable the specific Code Analysis warning (C26819)
    #pragma warning(disable : 26819) 
    
    // Optional: Disable other common external lib warnings if they appear
    #pragma warning(disable : 26495) // Variable is uninitialized
    #pragma warning(disable : 26451) // Arithmetic overflow
    #pragma warning(disable : 26813) // Bitwise and  
    #pragma warning(disable : 26495) // Member variable is uninitialized
    #pragma warning(disable : 26498)
    #pragma warning(disable : 6011)
#endif

// Include the actual library here
#include "exprtk.hpp"

#if defined(_MSC_VER)
    // Restore the warning state to protect YOUR code
    #pragma warning(pop)
#endif

#endif // SILENT_EXPRTK_HPP